database-type: boltdb

# persistence-type: local
root-directory: data
persistence-type: s3
# persistence-type: openstack

#aws
s3:
  # endpoint:
  access-key-id: AKIAIUC2R3AVIIJWTTLQ
  secret-key: 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
  region: us-west-2
  bucket-name: test-past3
# AWS_ACCESS_KEY_ID:  AKIAIUC2R3AVIIJWTTLQ
# AWS_SECRET_ACCESS_KEY:  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
# AWS_REGION: us-west-2
# AWS_S3_BUCKET: test-past3

#minio
# AWS_ACCESS_KEY_ID:  PIYBOILAKIFLTJHWXKCY
# AWS_SECRET_ACCESS_KEY:  tSFgFhSrkP4PwnvL9DvT9cgNUW//F3KFz2jgeVw/
# AWS_REGION: us-east-1
# AWS_S3_BUCKET: test
# AWS_ENDPOINT: http://127.0.0.1:9000



#openstack
openstack:
  identity-endpoint: "https://auth.cloud.ovh.net/v2.0/"
  username:         "nGaW4ryDxkz3"
  password:         "GmEhvEHWMzwheeJB6hRz8q283HNubYC2"
  tenant-id:         "74439eb9176b44c78f1a279cb21f554d"
  tenant-name:       "5129921842576950"
  bucket-name: "bucket-name"


app-metadata: app_metadata
forms-metadata: forms_metadata
workspaces-metadata: workspaces_metadata
workspaces-container: workspaces_container
users-bucket: users_bucket

auth0-client-secret: jb5NjpdYD9LeKKHlwNQdE2UrtX5CwAfpqsmRelbKps1U_92UpxUqKggVyX9WcGCx
auth0-api-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6IlF6TTBOVFl4TXpVek9VRXpNa1ExUlVNNU5UQTFSRGN3TURaQlF6WTRPVEkwUWpreFJUVTNSZyJ9.eyJpc3MiOiJodHRwczovL2VtaWtyYS5hdXRoMC5jb20vIiwic3ViIjoiWlc5WTJWSlh3TWRqZkliT3lVT1QzZ0paTk5KZm9PQk9AY2xpZW50cyIsImF1ZCI6Imh0dHBzOi8vZW1pa3JhLmF1dGgwLmNvbS9hcGkvdjIvIiwiZXhwIjoxNTgyODc5ODM5LCJpYXQiOjE0OTY0Nzk4MzksInNjb3BlIjoicmVhZDpjbGllbnRfZ3JhbnRzIGNyZWF0ZTpjbGllbnRfZ3JhbnRzIGRlbGV0ZTpjbGllbnRfZ3JhbnRzIHVwZGF0ZTpjbGllbnRfZ3JhbnRzIHJlYWQ6dXNlcnMgdXBkYXRlOnVzZXJzIGRlbGV0ZTp1c2VycyBjcmVhdGU6dXNlcnMgcmVhZDp1c2Vyc19hcHBfbWV0YWRhdGEgdXBkYXRlOnVzZXJzX2FwcF9tZXRhZGF0YSBkZWxldGU6dXNlcnNfYXBwX21ldGFkYXRhIGNyZWF0ZTp1c2Vyc19hcHBfbWV0YWRhdGEgY3JlYXRlOnVzZXJfdGlja2V0cyByZWFkOmNsaWVudHMgdXBkYXRlOmNsaWVudHMgZGVsZXRlOmNsaWVudHMgY3JlYXRlOmNsaWVudHMgcmVhZDpjbGllbnRfa2V5cyB1cGRhdGU6Y2xpZW50X2tleXMgZGVsZXRlOmNsaWVudF9rZXlzIGNyZWF0ZTpjbGllbnRfa2V5cyByZWFkOmNvbm5lY3Rpb25zIHVwZGF0ZTpjb25uZWN0aW9ucyBkZWxldGU6Y29ubmVjdGlvbnMgY3JlYXRlOmNvbm5lY3Rpb25zIHJlYWQ6cmVzb3VyY2Vfc2VydmVycyB1cGRhdGU6cmVzb3VyY2Vfc2VydmVycyBkZWxldGU6cmVzb3VyY2Vfc2VydmVycyBjcmVhdGU6cmVzb3VyY2Vfc2VydmVycyByZWFkOmRldmljZV9jcmVkZW50aWFscyB1cGRhdGU6ZGV2aWNlX2NyZWRlbnRpYWxzIGRlbGV0ZTpkZXZpY2VfY3JlZGVudGlhbHMgY3JlYXRlOmRldmljZV9jcmVkZW50aWFscyByZWFkOnJ1bGVzIHVwZGF0ZTpydWxlcyBkZWxldGU6cnVsZXMgY3JlYXRlOnJ1bGVzIHJlYWQ6ZW1haWxfcHJvdmlkZXIgdXBkYXRlOmVtYWlsX3Byb3ZpZGVyIGRlbGV0ZTplbWFpbF9wcm92aWRlciBjcmVhdGU6ZW1haWxfcHJvdmlkZXIgYmxhY2tsaXN0OnRva2VucyByZWFkOnN0YXRzIHJlYWQ6dGVuYW50X3NldHRpbmdzIHVwZGF0ZTp0ZW5hbnRfc2V0dGluZ3MgcmVhZDpsb2dzIHJlYWQ6c2hpZWxkcyBjcmVhdGU6c2hpZWxkcyBkZWxldGU6c2hpZWxkcyB1cGRhdGU6dHJpZ2dlcnMgcmVhZDp0cmlnZ2VycyByZWFkOmdyYW50cyBkZWxldGU6Z3JhbnRzIHJlYWQ6Z3VhcmRpYW5fZmFjdG9ycyB1cGRhdGU6Z3VhcmRpYW5fZmFjdG9ycyByZWFkOmd1YXJkaWFuX2Vucm9sbG1lbnRzIGRlbGV0ZTpndWFyZGlhbl9lbnJvbGxtZW50cyBjcmVhdGU6Z3VhcmRpYW5fZW5yb2xsbWVudF90aWNrZXRzIHJlYWQ6dXNlcl9pZHBfdG9rZW5zIn0.g0BhfrJN6dnQCaw6i1Do-OqlSZBKHOmEfue1Sy0xleKDlvtLujjyy19a1XUcp4IflpRRorhD4D6fTIwc2eeFSJiSbZvFeHW574eAYo88-6y05n_NVpmQVtS1VWJVkaicdd7DhQSWqbBT8VU0UGeB_KjJb5x7xU-yR4V1o6w7kwGZwV0iujJN3XVNuQWwd_t2XqNA-491KNLTPnY00rp_cct8Ru4rZYYNGMskBmGqYyHs9g-XtfcFa0_IeXjUnjaP8SFGK_FjsRER3QWDBaE2CfMDPxxdggmBaiG0yjPmnUbxQLnTpmJKKNTUF-4GM4OzFRZlrQGRa88tWqkXJJnHzQ
